name: tema_filme
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  http: ^0.12.2
  url_launcher: ^5.7.10
  flutter_redux: ^0.6.0
  redux_thunk: ^0.3.0
  build_runner: any
  json_serializable: any
  built_value_generator: ^7.1.0
  redux: any
  freezed_annotation: ^0.12.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: any

flutter:
  uses-material-design: true
